services:
  _defaults:
    autowire: true
    autoconfigure: true


#    sarbacane.example:
#        class: Acme\SarbacaneBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
